import type { GroomingStep, GroomingStatus, PaketGrooming, GroomingSession } from '@/types/pos'

export const GROOMING_STEPS: GroomingStep[] = [
  'check_in',
  'bathing',
  'drying',
  'styling',
  'finishing',
  'done',
]

export const GROOMING_STEP_LABELS: Record<GroomingStep, string> = {
  check_in: 'Check-in & Kondisi Awal',
  bathing: 'Mandi / Bathing',
  drying: 'Pengeringan / Blow Dry',
  styling: 'Styling / Cukur Bulu',
  finishing: 'Finishing Touch & Parfum',
  done: 'Selesai & Siap Dijemput ✨',
}

export const GROOMING_STEP_SHORT_LABELS: Record<GroomingStep, string> = {
  check_in: 'Check-In',
  bathing: 'Mandi',
  drying: 'Kering',
  styling: 'Styling',
  finishing: 'Finishing',
  done: 'Selesai',
}

export const GROOMING_STEP_EMOJI: Record<GroomingStep, string> = {
  check_in: '📋',
  bathing: '🛁',
  drying: '💨',
  styling: '✂️',
  finishing: '✨',
  done: '🎉',
}

export const GROOMING_STATUS_LABELS: Record<GroomingStatus, string> = {
  antrian: 'Dalam Antrian',
  dikerjakan: 'Sedang Dikerjakan',
  selesai: 'Selesai Pengerjaan',
  dijemput: 'Sudah Dijemput',
  dibatalkan: 'Dibatalkan',
}

export const DEFAULT_PAKET_GROOMING: PaketGrooming[] = [
  {
    id: 'pkg-1',
    nama: 'Mandi Sehat / Biasa',
    harga: 65000,
    deskripsi: 'Shampoo premium, conditioner, bersihkan telinga, potong kuku, blow dry',
    durasi_estimasi: 45,
    aktif: true,
  },
  {
    id: 'pkg-2',
    nama: 'Mandi Kutu / Jamur',
    harga: 85000,
    deskripsi: 'Shampoo obat treatment, bilas bersih, potong kuku, blow dry',
    durasi_estimasi: 60,
    aktif: true,
  },
  {
    id: 'pkg-3',
    nama: 'Full Grooming',
    harga: 120000,
    deskripsi: 'Mandi lengkap, potong kuku, styling/cukur rapi, parfum cat-safe',
    durasi_estimasi: 90,
    aktif: true,
  },
  {
    id: 'pkg-4',
    nama: 'Cukur Gundul / Lion Cut',
    harga: 100000,
    deskripsi: 'Shaving bulu gimbal/lion cut + mandi antiseptic',
    durasi_estimasi: 75,
    aktif: true,
  },
]

// Initial demo sessions for preview before DB migrations are run
export const DEMO_GROOMING_SESSIONS: GroomingSession[] = [
  {
    id: 'demo-grm-1',
    owner_id: 'own-1',
    cat_id: 'cat-1',
    paket: 'Full Grooming',
    harga: 120000,
    kondisi_awal: 'Bulu sedikit gimbal di leher, jamur kering di telinga kiri',
    catatan: 'Tolong jangan terlalu tipis di bagian ekor ya kak',
    tanggal: new Date().toISOString().split('T')[0],
    waktu_masuk: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    estimasi_selesai: new Date(Date.now() + 35 * 60 * 1000).toISOString(),
    status: 'dikerjakan',
    current_step: 'drying',
    public_token: 'live-demo-token-milo-01',
    sudah_bayar: true,
    metode_bayar: 'QRIS',
    groomer_name: 'Budi (Groomer)',
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    owner: {
      id: 'own-1',
      nama: 'Fara Nabila',
      no_wa: '081234567890',
      created_at: new Date().toISOString(),
    },
    cat: {
      id: 'cat-1',
      owner_id: 'own-1',
      nama: 'Milo',
      ras: 'British Shorthair',
      jenis_kelamin: 'Jantan',
      warna: 'Silver Tabby',
      foto_url: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80',
      created_at: new Date().toISOString(),
    },
    progress: [
      {
        id: 'prog-1',
        session_id: 'demo-grm-1',
        step: 'check_in',
        catatan: 'Kucing tiba dalam keadaan tenang, kondisi fisik dicek & dicatat.',
        foto_url: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80',
        created_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
      },
      {
        id: 'prog-2',
        session_id: 'demo-grm-1',
        step: 'bathing',
        catatan: 'Proses mandi dengan sampo antibakteri dan bilasan hangat selesai.',
        foto_url: 'https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=600&auto=format&fit=crop&q=80',
        created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
      },
      {
        id: 'prog-3',
        session_id: 'demo-grm-1',
        step: 'drying',
        catatan: 'Sedang proses pengeringan menggunakan blower khusus kucing (low noise).',
        foto_url: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=600&auto=format&fit=crop&q=80',
        created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'demo-grm-2',
    owner_id: 'own-2',
    cat_id: 'cat-2',
    paket: 'Mandi Kutu / Jamur',
    harga: 85000,
    kondisi_awal: 'Kutu ringan di punggung, tidak ada luka',
    catatan: 'Shampo kutu anti perih',
    tanggal: new Date().toISOString().split('T')[0],
    waktu_masuk: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    status: 'antrian',
    current_step: 'check_in',
    public_token: 'live-demo-token-luna-02',
    sudah_bayar: false,
    groomer_name: 'Dewi (Groomer)',
    created_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    owner: {
      id: 'own-2',
      nama: 'Andi Pratama',
      no_wa: '085712345678',
      created_at: new Date().toISOString(),
    },
    cat: {
      id: 'cat-2',
      owner_id: 'own-2',
      nama: 'Luna',
      ras: 'Persia Medium',
      jenis_kelamin: 'Betina',
      warna: 'White Calico',
      foto_url: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&auto=format&fit=crop&q=80',
      created_at: new Date().toISOString(),
    },
    progress: [
      {
        id: 'prog-4',
        session_id: 'demo-grm-2',
        step: 'check_in',
        catatan: 'Luna sudah masuk antrian ruang grooming 1.',
        foto_url: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&auto=format&fit=crop&q=80',
        created_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'demo-grm-3',
    owner_id: 'own-3',
    cat_id: 'cat-3',
    paket: 'Mandi Sehat / Biasa',
    harga: 65000,
    kondisi_awal: 'Bulu bersih, kuku panjang',
    tanggal: new Date().toISOString().split('T')[0],
    waktu_masuk: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    waktu_selesai: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    status: 'selesai',
    current_step: 'done',
    public_token: 'live-demo-token-oliver-03',
    sudah_bayar: true,
    metode_bayar: 'Tunai',
    groomer_name: 'Budi (Groomer)',
    created_at: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    owner: {
      id: 'own-3',
      nama: 'Siti Rahma',
      no_wa: '089612345678',
      created_at: new Date().toISOString(),
    },
    cat: {
      id: 'cat-3',
      owner_id: 'own-3',
      nama: 'Oliver',
      ras: 'Domestic Mix',
      jenis_kelamin: 'Jantan',
      warna: 'Orange Tabby',
      foto_url: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=600&auto=format&fit=crop&q=80',
      created_at: new Date().toISOString(),
    },
    progress: [
      {
        id: 'prog-5',
        session_id: 'demo-grm-3',
        step: 'check_in',
        catatan: 'Oliver siap mandi.',
        created_at: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
      },
      {
        id: 'prog-6',
        session_id: 'demo-grm-3',
        step: 'done',
        catatan: 'Oliver sudah wangi, potong kuku rapi, dan siap dijemput!',
        foto_url: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=600&auto=format&fit=crop&q=80',
        created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      },
    ],
  },
]
